sonar.projectKey=open-supervisor-sse-server
sonar.projectName=open-supervisor SSE Server
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.cpd.exclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
