export enum RejectionReason {
  EMPLOYEE_NOT_ACTIVE = 'EMPLOYEE_NOT_ACTIVE',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  EMPLOYEE_NOT_FOUND = 'EMPLOYEE_NOT_FOUND',
  AD_LOOKUP_FAILED = 'AD_LOOKUP_FAILED',
}
