sonar.projectKey=open-supervisor-authorization-service
sonar.projectName=open-supervisor Authorization Service
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.cpd.exclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=src/coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
